import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {accessGate} from '../access.mjs';
async function fixture(t,options){const gate=accessGate(options);const server=http.createServer(async(req,res)=>{if(await gate(req,res,new URL(req.url,'http://localhost')))return;res.end('protected-data');});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));return `http://127.0.0.1:${server.address().port}`;}
test('all paths protected; login grants session, forged cookies fail and logout clears it',async t=>{const base=await fixture(t,{enabled:true,password:'test-only-password'});for(const path of ['/data/snapshot.json','/data/states.json','/api/events','/app.js']){const r=await fetch(base+path);assert.equal(r.status,401);assert.equal(r.headers.get('cache-control'),'private, no-store');assert.ok(!(await r.text()).includes('protected-data'));}const bad=await fetch(base+'/login',{method:'POST',body:'password=wrong'});assert.equal(bad.status,401);const good=await fetch(base+'/login',{method:'POST',body:'password=test-only-password',redirect:'manual'});assert.equal(good.status,303);const cookie=good.headers.get('set-cookie');assert.match(cookie,/HttpOnly/);assert.match(cookie,/SameSite=Lax/);assert.equal(await(await fetch(base+'/data/snapshot.json',{headers:{cookie}})).text(),'protected-data');assert.equal((await fetch(base+'/data/snapshot.json',{headers:{cookie:'bip_session=9999999999.fake'}})).status,401);assert.match((await fetch(base+'/logout',{redirect:'manual'})).headers.get('set-cookie'),/Max-Age=0/);});
test('missing secret fails closed; explicit public mode opens data',async t=>{let b=await fixture(t,{enabled:true});assert.equal((await fetch(b)).status,503);b=await fixture(t,{enabled:false});assert.equal(await(await fetch(b)).text(),'protected-data');});
test('wrong password is throttled and cross-origin login rejected',async t=>{const b=await fixture(t,{enabled:true,password:'test-only-password'});assert.equal((await fetch(b+'/login',{method:'POST',headers:{Origin:'https://example.com'},body:'password=test-only-password'})).status,403);for(let i=0;i<10;i++)assert.equal((await fetch(b+'/login',{method:'POST',body:'password=wrong'})).status,401);assert.equal((await fetch(b+'/login',{method:'POST',body:'password=wrong'})).status,429);});
test('trusted public origin permits login behind proxy with internal Host',async t=>{const b=await fixture(t,{enabled:true,password:'test-only-password',secure:true,publicOrigin:'https://preview.example.com'});const r=await fetch(b+'/login',{method:'POST',headers:{Origin:'https://preview.example.com'},body:'password=test-only-password',redirect:'manual'});assert.equal(r.status,303);assert.match(r.headers.get('set-cookie'),/Secure/);const bad=await fetch(b+'/login',{method:'POST',headers:{Origin:'https://attacker.example.com'},body:'password=test-only-password',redirect:'manual'});assert.equal(bad.status,403);});
test('embedded opaque-origin login still requires the shared password',async t=>{const b=await fixture(t,{enabled:true,password:'test-only-password',publicOrigin:'https://preview.example.com'});for(const [password,status] of [['wrong',401],['test-only-password',303]])assert.equal((await fetch(b+'/login',{method:'POST',headers:{Origin:'null'},body:new URLSearchParams({password}),redirect:'manual'})).status,status);});
